Feature/game result
kmu-system-newest-tech-23-team-b/final-project pull request #13
Opened 2023-04-27 06:31 UTC by ISCMSHY

게임 종료 이벤트, 타이머, 게임 종료 UI, 스코어 및 타이머 UI 및 연동, 게임 재시작 기능 추가했습니다.
그리고 #11 이슈 11번 버그에 대해서도 수정 완료했습니다.

2023-04-27 12:22 UTC, minwook-shin commented
@ISCMSHY 
develop 최신 코드를 반영했고, 충돌을 해결하는 과정에서 코드가 동작하도록 커밋을 추가했습니다.

2023-04-27 12:27 UTC, minwook-shin commented on src/system_module/player.rs
> +const ENTER: u8 = 1 << 5; // game over -> game ready
스페이스와 엔터키에 대한 설명이 UI 상에 존재한다면 처음 시작할 때 왜 안 움직이는 지에 대한 의문이 없을 것 같습니다 :)

2023-04-27 12:30 UTC, minwook-shin commented on src/system_module/player.rs
> +             mut quit_button_query: Query<&Interaction,(Changed<Interaction>, With<QuitButton>)>
warning: variable does not need to be mutable 경고가 발생해서 mut 을 제거해주시면 될 것 같습니다.

2023-04-28 19:24 UTC, ISCMSHY commented
@minwook-shin @Winjae @wsb8618 
마지막 push까지 진행해서 score 화면 출력 및 게임 결과 파일 저장, peer_id parsing까지는 구현 완료했습니다. 다만 결과 출력 시 상대방 peer_id도 알아야 한다는 점과 score sync를 맞추기 위해서는 #17 을 해결해야 되서 해당 issue만 해결 한 후 코드만 추가하면 끝날 것 같습니다.

2023-04-29 04:55 UTC, minwook-shin requested changes

2023-04-29 04:55 UTC, minwook-shin commented on src/system_module/network.rs
> +                PlayerType::Remote(peer_id) => { player_id.id_0 = peer_id.0.to_string(); }
player_id.id_0 이 자신인지 상대방인지 표기가 명확하면 좋을 것 같습니다 :)

2023-04-29 04:55 UTC, minwook-shin commented on .gitignore
> +/game_result/
해당 폴더 대신 실행 위치에 result.txt 파일이 생성되던데 gitignore 에 result.txt 도 처리해주시면 좋을 것 같습니다 :)

2023-04-29 10:12 UTC, ISCMSHY commented on src/system_module/network.rs
> +                PlayerType::Remote(peer_id) => { player_id.id_0 = peer_id.0.to_string(); }
넵 변수명에 명시해 놓겠습니다

2023-04-29 12:23 UTC, merged